from pytorchrl.agent.algorithms.policy_loss_addons.base import PolicyLossAddOn
from pytorchrl.agent.algorithms.policy_loss_addons.kv_similarity import AttractionKL
from pytorchrl.agent.algorithms.policy_loss_addons.kv_similarity import RepulsionKL
